Month 8/step 2
imynel/react-stellar-burger pull request #5
Opened 2023-09-02 01:54 UTC by imynel

2023-09-02 09:43 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Редьюсеры - чистые функции
- Созданы все необходимые типы экшенов
- Очищаете конструктор после оформления заказа

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- При перемещении ингредиентов внутри конструктора происходит  ошибка

<img width="1039" alt="Снимок экрана 2023-09-02 в 12 33 37" src="https://github.com/imynel/react-stellar-burger/assets/60173362/a99799fa-17ee-4ae5-b596-5a07bab80582">

- У ингредиентов должен обновляться счетчик при добавлении их в конструктор бургера. 
- При скролле внутри компонента `BurgerIngredients` самый ближний к верхней левой границе заголовок контейнера должен становится активным
- У некоторых компонентов с пропсами нет `propTypes`
- Использовать моковые данные на данном этапе уже нельзя, все данные должны браться с сервера
- разделите редьюсер на несколько 
- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-02 09:43 UTC, andryxxa93 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  dataIngredients: PropTypes.array,
**Можно лучше**
`dataIngredients ` не принимается компонентом в качестве пропса, поэтому его следует удалить

2023-09-02 09:43 UTC, andryxxa93 commented on src/components/Ingredient/Ingredient.jsx
> +const Ingredient = ({ item, handleOpen }) => {
**Надо исправить**

для этого компонента так же нужно описать PropTypes

2023-09-02 09:43 UTC, andryxxa93 commented on src/components/IngregientsInConstructor/IngregientsInConstructor.jsx
>  IngregientsInConstructor.propTypes = {
**Необходимо исправить**
в `propTypes` указан не весь список пропсов

2023-09-02 09:43 UTC, andryxxa93 commented on src/services/reducers/ingredients.js
> +        "_id":"60666c42cc7b410027a1a9b1",
**Необходимо исправить**
Использовать моковые данные на данном этапе уже нельзя, все данные должны браться с сервера

2023-09-02 09:43 UTC, andryxxa93 commented on src/services/reducers/ingredients.js
> +import { GET_INGREDIENTS_FAILED, GET_INGREDIENTS_SUCCESS, GET_INGREDIENTS_REQUEST } from "../actions/ingredients"
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2023-09-04 14:00 UTC, imynel commented on src/services/reducers/ingredients.js
> +import { GET_INGREDIENTS_FAILED, GET_INGREDIENTS_SUCCESS, GET_INGREDIENTS_REQUEST } from "../actions/ingredients"
я вроде бы всё совместил, разделил, но не могу понять куда деть initialState, у меня просто не появляется стор

2023-09-05 06:02 UTC, andryxxa93 commented
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers


Если у вас что-то не получается вы всегда можете обратиться к своему наставнику.

2023-09-07 05:36 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-09-08 10:30 UTC, merged